### ISSUE TITLE
Failed to decrypt 'endpoint_key': AccessDeniedException

### ISSUE THREAD

**Issue by schauhandiv** [ferhatvurucu/terraform-aws-kinesis-firehose-datadog#1]
I created the KMS key and use data "aws_kms_ciphertext" to encrypt the datadog apikey. when i run terraform apply, it gives me this error.... 
Error: Failed to decrypt 'endpoint_key': AccessDeniedException: The ciphertext refers to a customer master key that does not exist, does not exist in this region, or you are not allowed to access.

**Comment by ferhatvurucu** [comment]
It looks like an IAM permission issue. Can you check if "kms:Decrypt" action is allowed in your policy?

**Comment by schauhandiv** [comment]
Yes, I added the Decrypt to the policy (for root) and don't see that error now (in tf plan). But I am still unclear as to what role does this module use to create the resources. Sorry I am new to terraform so please excuse my ignorance. 

Also, I noticed that the "kinesis_firehose_role_name" it created got created in our 'main' account. I was expecting it to be created in our 'test' account. We have our main account and from there we use terraform workspaces to switch to a different account. I switched to our 'test' account, and ran tf apply. It created that role in our 'main' account. A few other resources during the same tf apply got created correctly in the 'test' account. Is this expected behavior of this module?

**Comment by ferhatvurucu** [comment]
I suggest you to check terraform workspaces documentation. Closing the issue.
